# Generated by Django 3.2.16 on 2023-07-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=300)),
                ('card_information', models.IntegerField()),
                ('card_date', models.DateTimeField()),
                ('card_cvc', models.IntegerField()),
                ('card_owner_name', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_owner_id', models.IntegerField()),
            ],
        ),
    ]
