# Generated by Django 3.2.16 on 2023-07-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
