# Generated by Django 3.2.16 on 2023-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentinformation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
