# Generated by Django 3.2.16 on 2023-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentinformation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('product_desc', models.TextField()),
                ('product_price', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(null=True)),
            ],
        ),
    ]
