# Generated by Django 3.2.16 on 2023-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentinformation_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('creator_id', models.IntegerField(null=True)),
                ('subscriber_id', models.IntegerField()),
            ],
        ),
    ]
