# Generated by Django 3.2.16 on 2023-08-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscribeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeuser',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscribeuser',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
