# Generated by Django 3.2.16 on 2023-08-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20230804_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_date',
            field=models.CharField(max_length=5),
        ),
    ]
