# Generated by Django 3.2.16 on 2023-07-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeBlockUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
