# Generated by Django 3.2.16 on 2023-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('is_free', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('post_picture', models.ImageField(blank=True, default='post_pic.jpg', null=True, upload_to='post_pictures/')),
                ('is_bookmark', models.BooleanField(default=False)),
                ('is_like', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
