# Generated by Django 3.2.16 on 2023-07-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='post_pictures/'),
        ),
    ]
