# Generated by Django 3.2.16 on 2023-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0002_alter_post_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeBookmarkPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_bookmark', models.BooleanField(default=False)),
                ('is_like', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeBlockUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_bookmark',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_like',
        ),
    ]
