# Generated by Django 3.2.16 on 2023-07-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0003_auto_20230711_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeBlockUser',
        ),
    ]
