# Generated by Django 3.2.16 on 2023-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.IntegerField(),
        ),
    ]
