# Generated by Django 3.2.16 on 2023-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0007_alter_comments_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_body', models.TextField()),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
