# Generated by Django 3.2.16 on 2023-07-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0009_notifications_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='current_user',
            field=models.IntegerField(null=True),
        ),
    ]
