# Generated by Django 3.2.16 on 2023-07-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0010_notifications_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='current_user',
        ),
    ]
