# Generated by Django 3.2.16 on 2023-08-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0011_remove_notifications_current_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_bookmark', models.BooleanField(default=False)),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_like', models.BooleanField(default=False)),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='LikeBookmarkPost',
        ),
    ]
