# Generated by Django 3.2.16 on 2023-08-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230803_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeUser',
        ),
    ]
